acnh/urls.py
from django.urls import path
from . import views

app_name = 'acnh'
urlpatterns = [
    # ex: /acnh/
    path('', views.index, name='index')
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.index, name='home'),
    # path('work/', views.work, name='work')
]

rich_banana/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from rest_framework import routers
from register import views as registerView
from users import views as usersView

router = routers.DefaultRouter()
router.register(r'users', usersView.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', registerView.register, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('acnh/', include('acnh.urls')),
    path('', include('portfolio.urls')),
    path('api/', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # ex: /users/search/
    path('search/', views.search, name='search'),
    # ex: /users/5
    path('<int:pk>', views.UserView.as_view(), name='info')
]

acnh/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, phone, password, first_name='', last_name='', date_of_birth=None, email=None, address=''):
        """
        Creates and saves a User with the given phone number and pw
        """
        if not phone:
            raise ValueError(_('Phone can not be empty'))
        user = self.model(
            phone = phone,
            first_name = first_name,
            last_name = last_name,
            date_of_birth = date_of_birth,
            email = self.normalize_email(email),
            address = address,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password, first_name='', last_name='', date_of_birth=None, email=None, address=''):
        """
        Creates and saves a Superuser with the given phone and password.
        """

        user = self.create_user(
            phone,
            first_name = first_name,
            last_name = last_name,
            date_of_birth = date_of_birth,
            email = self.normalize_email(email),
            address = address,
            password = password
        )

        user.points_buy = 0
        user.points_img = 0
        user.points_vid = 0
        user.is_admin = True
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser, PermissionsMixin):
    phone = models.CharField(
        verbose_name = _('Phone Number'),
        max_length = 20,
        unique = True
    )

    first_name = models.CharField(
        verbose_name = _('First Name'),
        max_length = 20,
        blank = True
    )

    last_name = models.CharField(
        verbose_name = _('Last Name'),
        max_length = 20,
        blank = True
    )

    date_of_birth = models.DateField(
        verbose_name = _('Birthday'),
        null = True,
        blank = True
    )

    email = models.EmailField(
        verbose_name = _('Email Address'),
        max_length = 255,
        null = True,
        blank = True
    )

    address = models.TextField(
        verbose_name = _('Address'),
        blank = True
    )

    points_buy = models.PositiveIntegerField(
        default=0,
        verbose_name = _('Direct Points')
    )

    points_img = models.PositiveIntegerField(
        default=0,
        verbose_name = _('ImgReview Points')
    )

    points_vid = models.PositiveIntegerField(
        default=0,
        verbose_name = _('VidReview Points')
    )

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    @property
    def points_total(self):
        return self.points_buy + self.points_img + self.points_vid


    objects = MyUserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.phone

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from users.models import MyUser

class registerForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ["phone", "email", "password1", "password2"]

acnh/views.py
from django.shortcuts import render
# import requests

# Create your views here.
def index(req):
    return render(req, 'acnh/index.html')
    # fish_data = {}
    # name_set = {}
    # if 'fish_name' in req.GET:
    #     fish_name = req.GET['fish_name']
    #     url = 'http://acnhapi.com/v1/fish/%s' % fish_name
    #     response = requests.get(url)
    #     fish_data = response.json()
    #     name_set = fish_data['name']['name-CNzh']
    # return render(req, 'acnh/index.html', {
    #     'fish_name': name_set,
    #     'fish_data': fish_data
    #     })

portfolio/views.py
from django.shortcuts import render

# Create your views here.
def index(req):
    return render(req, 'portfolio/index.html', {'about': 'active'})

# def work(req):
#     return render(req, 'portfolio/work.html', {'work': 'active'})

register/views.py
from django.shortcuts import render, redirect
from .forms import registerForm

# Create your views here.
def register(res):
    if res.method == 'POST':
        form = registerForm(res.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = registerForm()
    return render(res, 'register/register.html', {'form': form})

users/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, get_object_or_404
from rest_framework import viewsets
from .serializers import UserSerializer
from .models import MyUser

# Create your views here.
class UserView(generic.DetailView):
    model = MyUser
    template_name = 'users/info.html'
    context_object_name = 'user'

# Create user API view
class UserViewSet(viewsets.ModelViewSet):
    queryset = MyUser.objects.all()
    serializer_class = UserSerializer

def search(res):
    mode = res.GET.get('mode', '')
    if res.method == 'POST':
        try:
            user = get_object_or_404(MyUser, phone=res.POST['phone'])
        except:
            # Redisplay the search form with error_message
            return render(res, 'users/search.html', {
                'error_message': "User not exist.",
                'mode': mode
            })
        else: return HttpResponseRedirect(reverse('users:info', args=(user.id,)))
    else: return render(res, 'users/search.html', {'mode': mode})

acnh/templates/acnh/index.html
{% extends 'base.html' %}

{% block title %}
<title>Animal Crossing New Horizons</title>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'acnh.css'%}">
<div id="app"></div>
{% load static %}
<script src="{% static 'acnh/main.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="content-block title">
  <div class="up-buffer"></div>
  <div class="content">
    <h3>Hi, I'm Yiqi</h3>  
    <br>
    <h5>An explorer of the world</h5>
  </div>
  <div class="down-arrow">
    <a href="#about"><i data-feather="chevron-down"></i></a>
  </div> 
</div>

<div class="content-block" id="about">
  <div class="content"> 
    <div class="section-title">
      <h3>About me</h3>  
      <br>
      <hr>
      <br>
    </div>
    

    <div class="about">
      
      <div class="left">
        <p>I am a developer based in Montreal, who always attracted to technology and interesting little things. Love to try new stuff and push my limits to see what I am capable of. Work hard, play hard!</p>
      </div>
      
      <div class="right">
        <table class="table table-borderless">
          <tbody>

            <tr>
              <td style="width: 16.66%">Python</td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 90%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>

            <tr>
              <td style="width: 16.66%">JS</td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 80%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>

            <tr>
              <td style="width: 16.66%">HTML</td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 75%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>

            <tr>
              <td style="width: 16.66%">CSS</td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 75%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>

            <tr>
              <td style="width: 16.66%">Java</td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 50%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>

            <tr>
              <td style="width: 16.66%">SQL</td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 40%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
       
      </div>  
    
    </div>
    
  </div>


  <!-- Need a down-arrow button to nav to next section (Project Section) -->

</div>

<div class="content-block" id="project">
  <div class="content">
    <div class="section-title">
      <h3>Projects</h3>
      <br>
      <hr>
    </div>
  </div>
</div>

<div class="project-block">

  <!-- Animao Crossing Project -->
  <div class="content acnh bordered">
    <h3>Animal Crossing NH</h3>
    <p>Toy React project for Animal Crossing: New Horizons.</p>
    <figure>
      <img src="{% static 'img/acnh_demo.jpg' %}" alt="acnh">
    </figure>
    <a href="{% url 'acnh:index' %}" target="_blank" type="button" class="btn btn-success">View Demo</a>
  </div>

  <!-- Glass Retailer Website Project -->
  <div class="content mao bordered">
    <h3>MAO glasses retailer partial</h3>
    <p>A glasses online store with JS and handlebars hosted with Bigcommerce. The website is unavailable now but still have a demo of the lense selection section.</p>
    <figure>
      <img src="{% static 'img/mao_demo.jpg' %}" alt="mao">
    </figure>
    <a href="http://dev.yiqihuang.me/" target="_blank" type="button" class="btn btn-dark">View Demo</a>
  </div>

  <!-- Personal Blog Project -->
  <div class="content blog bordered">
    <h3>Personal Blog</h3>
    <p>Simple blog page using Vanilla JS and bootstrap, hosted on github page with a python blog empty-template generator.</p>
    <figure>
      <img src="{% static 'img/blog_demo.jpg' %}" alt="blog">
    </figure>
    <a href="http://michuang.github.io/" target="_blank" type="button" class="btn btn-warning">View Demo</a>
  </div>

  <!-- User Info Lookup Project -->
  <div class="content userInfo bordered">
    <h3>User Info Lookup Tool</h3>
    <p>Single page web app provide real customers an interface to check their in store points. Built with Django as backend and API with user info as well as admin portal to manage users. PostgreSQL for the database runing on AWS RDs. </p>
    <figure>
      <img src="{% static 'img/img_placeholder.jpg' %}" alt="userInfo">
    </figure>
    <a href="{% url 'users:search' %}?mode=demo" target="_blank" type="button" class="btn btn-danger">View Demo</a>
  </div>

  <!-- Youtube Thumbnail Grabber Project -->
  <div class="content thumbnail-grabber bordered">
    <h3>Youtube Thumbnail Grabber</h3>
    <p>Single page web app to grabber youtube videos. Use Python FastAPI to provide functions and ajax to fetch the thumbnail</p>
    <figure>
      <img src="{% static 'img/img_placeholder.jpg' %}" alt="thumbnail-grabber">
    </figure>
    <a href="https://thumbnail-grabber.herokuapp.com/" target="_blank" type="button" class="btn btn-info">View Demo</a>
  </div>

  <!-- Countdown Timer Project -->
  <div class="content timer bordered">
    <h3>Simple Countdown Timer</h3>
    <p>A simple timer will countdown the time you set, and ring after times up.</p>
    <figure>
      <img src="{% static 'img/img_placeholder.jpg' %}" alt="timer">
    </figure>
    <a href="http://banana-timer.herokuapp.com/" target="_blank" type="button" class="btn btn-secondary">View Demo</a>
  </div>
</div>

<div class="content-block bottom">
  <div class="content">
    <h3>If you wanna know more about me.</h3>
  </div>
</div>


<div class="content-block social">
  <div class="content">
    <h3 style="color:lightslategrey">You can</h3>
    <div class="social-icon">
      <a href="https://github.com/MicHuang"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/yiqi-huang-a35837b4/"><i class="fab fa-linkedin"></i></a>
      <a href="mailto: yitsi.huang@gmail.com"><i class="fas fa-envelope-square"></i></a>
    </div>
  </div>
  
</div>

{% endblock %}

portfolio/templates/portfolio/work.html
{% extends 'base.html' %}

{% block content %}

<div class="content-block title">
  <div class="content">
    <h3>Projects</h3>
  </div>
</div>

<div class="content-block acnh">
  <div class="content">
    <h3>Animal Crossing NH</h3>
    <p>Toy React project for Animal Crossing: New Horizons.</p>
    <a href="{% url 'acnh:index' %}" target="_blank" type="button" class="btn btn-success">View Demo</a>
  </div>
</div>

<div class="content-block userInfo">
  <div class="content">
    <h3>User Info Lookup Tool</h3>
    <p>Single page web app provide real customers an interface to check their in store points. Built with Django as backend and API with user info as well as admin portal to manage users. PostgreSQL for the database runing on AWS RDs. </p>
    <a href="{% url 'users:search' %}?mode=demo" type="button" class="btn btn-danger">View Demo</a>
  </div>
</div>

<div class="content-block mao">
  <div class="content">
    <h3>MAO glasses retailer partial</h3>
    <p>A glasses online store with JS and handlebars hosted with Bigcommerce. The website is unavailable now but still have a demo of the lense selection section.</p>
    <a href="http://dev.micown.com/" target="_blank" type="button" class="btn btn-dark">View Demo</a>
  </div>
</div>


<div class="content-block blog">
  <div class="content">
    <h3>Personal Blog</h3>
    <p>Simple blog page using Vanilla JS and bootstrap, hosted on github page with a python blog empty-template generator.</p>
    <a href="http://michuang.github.io/" target="_blank" type="button" class="btn btn-warning">View Demo</a>
  </div>
</div>

<div class="content-block">
  <div class="content">
    <h3></h3>
    <p></p>
    <a href="mailto: yitsi.huang@gmail.com" type="button" class="btn btn-primary">Contact Me</a>
  </div>
</div>

{% endblock %}

register/templates/register/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Register</title>
{% endblock %}

{% block content%}

<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-8 mt-4">
      <form method="POST" action="/register/" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Register</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
<!doctype html>

<html lang="en">

<head>
  <!-- Required meta tags -->

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-173443629-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-173443629-1');
  </script>

  <!-- Google Ads -->
  <script data-ad-client="ca-pub-7242757743924339" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

  <!-- font awesome -->
  <script src="https://kit.fontawesome.com/a27cb38bbe.js" crossorigin="anonymous"></script>

  <!-- google font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- custome CSS -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'main.css' %}">

  <script src="https://unpkg.com/feather-icons"></script>

  {% block title %}
  <title>Yiqi Huang</title>
  {% endblock %}

</head>

<body>
  <div class="page-container">

    {% block navbar %}
    
    <nav class="navbar navbar-expand-sm nav-fix-top" id="navbar">
      <div class="container">
        <div class="navbar-brand" id="head-logo">
          <a href="{% url 'portfolio:home' %}">
            <span class="mask"></span>
            <span class="behind"></span>
          </a>
        </div>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <i data-feather="align-justify"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">

          <ul class="navbar-nav ml-auto">

            <li class="nav-item" data-toggle="collapse" data-target=".navbar-collapse.show">
              <a href="#about" class="nav-link">About</a>
            </li>

            <li class="nav-item" data-toggle="collapse" data-target=".navbar-collapse.show">
              <a href="#project" class="nav-link">Work</a>
            </li>

            <li class="nav-item" data-target=".navbar-collapse.show">
              <a href="#" class="nav-link {{notes}}">Notes</a>
            </li>


          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}

    <div class="main">
      {% block content %}
      <h1>Hello, world!</h1>
      {% endblock %}
    </div>



    <footer class="footer">
      <div class="container">
        <p>&copy; 2020 <a href="{% url 'portfolio:home' %}">Yiqi</a></p>
      </div>
    </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script>
      feather.replace()
    </script>
    <!-- custome JS -->
    <script src="{% static 'main.js' %}"></script>
  </div>
</body>

</html>

users/templates/users/info.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
<title>Info</title>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 mt-4">
      {% if user.first_name %}<p>{% blocktrans %}Welcome{% endblocktrans %} {{ user.first_name }}</p>{% endif %}
    </div>
    <div class="col-md-4 col-sm-10">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{% blocktrans %}You have{% endblocktrans %}: {{user.points_total}} point{{ user.points_total|pluralize }}</li>
      </ul>
    </div>
  </div>
  <hr>
  <div>
    <p><a href="{% url 'users:search' %}">Back</a> to search page.</p>
  </div>
</div>


{% endblock %}

users/templates/users/search.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
<title>Search</title>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}

<div class="container">
  <br>
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 mt-3">
      {% if error_message %}
      <div class="alert alert-danger col-md-4 col-sm-4 pb-0" role="alert">
        <p><strong>{{ error_message }}</strong></p>
      </div>
      {% endif %}
    </div>
    <form class="form-group col-md-4 col-sm-10" action="{% url 'users:search' %}" method="post">
      {% csrf_token %}

      <div class="input-group mb-3">
        <input type="tel" class="form-control" name="phone" placeholder="{% blocktrans %}Phone number{% endblocktrans %}...">
        <button class="btn" type="submit"><i data-feather="search"></i></button>
      </div>
    </form>

  </div>
  {% if mode %}
  <div style="color:lightgray">// Use 1234567 for testing.</div>
  {% endif %}
</div>

{% endblock %}